Oscar vega contrib#6
KarlHeitmann/survey_express_normal pull request #35
Opened 2021-04-13 02:50 UTC by OscarVegaV

2021-04-13 03:08 UTC, KarlHeitmann commented on app/views/devise/registrations/new.html.erb
> +    Para Agregar tu Gravatar, ingrese a este  <a href="https://wordpress.com/start/wpcc/oauth2-user?ref=oauth2&oauth2_redirect=https%3A%2F%2Fpublic-api.wordpress.com%2Foauth2%2Fauthorize%2F%3Fclient_
¡Muy bien! Excelente que mande a la página de gravatar en español. Esta aplicación es para la gente del curso, de habla hispana.

Bien por el detalle de colocar el target="_blank", la gracia es que como ese es un link exterior, debe abrir el link en una nueva pestaña.

2021-04-13 03:21 UTC, KarlHeitmann requested changes
Tenemos 3 puntos importantes a revisar:

- El CDN de Bootstrap. Pruebe eliminándolo del `app/views/layouts/application.html.erb` dejándolo así como estaba antes. Debería funcionar igual
- El uso de "usted" y "tú" debe ser consistente. Revise la redacción del texto que colocó en el formulario de registro y en el de edición de datos personales. Más información en los comentarios.

Está bueno con el alert de color gris. Destaca el mensaje. También estamos bien con los links, uno manda a registro de Gravatar y otro a la página de Gravatar. Muy bien por el detalle de colocar el link con el `target="_blank"` : cuando uno coloca links a páginas externas, de otras personas/dominios, se suele colocar el `target="_blank"` para que la página se abra en otra pestaña, para que el usuario pueda volver al sitio original y seguir navegando.

2021-04-13 03:21 UTC, KarlHeitmann commented on app/views/layouts/application.html.erb
> +    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css" integrity="sha384-B0vP5xmATw1+K9KRQjQERJvTumQW0nPEzvF6L/Z6nronJ3oUOFUFpCjEUQouq2+l" crossorig
¿Es realmente necesario colocar bootstrap acá? Yo lo coloqué en otro lugar para no usar el CDN, lo coloqué en `app/javascript/packs/application.js` . Pruebe borrando estas líneas, y compruebe que la aplicación siga funcionando.

2021-04-13 03:21 UTC, KarlHeitmann commented on app/views/devise/registrations/new.html.erb
> +    Para Agregar tu Gravatar, ingrese a este  <a href="https://wordpress.com/start/wpcc/oauth2-user?ref=oauth2&oauth2_redirect=https%3A%2F%2Fpublic-api.wordpress.com%2Foauth2%2Fauthorize%2F%3Fclient_
"Agregar" tiene que estar en minúsculas. "Gravatar" está bien que esté en con mayúscula en la letra "G".

La frase tiene que ser consistente: o se dirige al lector como "tú", o se dirige al lector con "usted". Escoger entre:

- Para agregar *tu* Gravatar, *ingresa* a este link...
- Para agregar *su* Gravatar, *ingrese* a este link...

2021-04-13 03:21 UTC, KarlHeitmann commented on app/views/users/edit.html.erb
> +    Para cambiar tu Gravatar, ingrese a este  <a href="https://es.gravatar.com/" class="alert-link" target="_blank">link</a>. y sigue las instrucciónes.
Igual que en el punto anterior. Debe ser consistente con el uso de "usted" o "tú". O tutea, o trata de usted.

2021-04-24 19:27 UTC, OscarVegaV commented on app/views/layouts/application.html.erb
> +    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css" integrity="sha384-B0vP5xmATw1+K9KRQjQERJvTumQW0nPEzvF6L/Z6nronJ3oUOFUFpCjEUQouq2+l" crossorig
borre las linas y funciona!

2021-04-24 19:28 UTC, OscarVegaV commented on app/views/users/edit.html.erb
> +    Para cambiar tu Gravatar, ingrese a este  <a href="https://es.gravatar.com/" class="alert-link" target="_blank">link</a>. y sigue las instrucciónes.
listo.

2021-04-25 22:01 UTC, KarlHeitmann approved these changes

2021-04-25 22:05 UTC, KarlHeitmann commented
Bien!! Super limpios los cambios.

2021-04-25 22:05 UTC, merged